image: node

cache:
  paths:
    - node_modules/
    - .next/cache/

pages:
  before_script:
    - npm install
    - npm run build
    - npm run export
  script:
    # - rm -rf public/*
    # - mv out/* public
  after_script:
    # - rm -rf out
    - ls -lah
  artifacts:
    paths:
      - public
  only:
    - main