image: node

cache:
  paths:
    - node_modules/
    - .next/cache/

pages:
  before_script:
    - npm install
    - npm run build
  script:
    - npm run build
    - ls -lah
  after_script:
    - rm -rf out
    - ls -lah public/
  artifacts:
    paths:
      - public
  only:
    - main