image: node

cache:
  paths:
    - node_modules/
    - .next/cache/

pages:
  before_script:
    - npm install
  script:
    # - rm -rf public/*
    # - mv out/* public
    # - npm run build
    - npm run build && next export
  after_script:
    # - rm -rf out
    - ls
    - ls out/
  artifacts:
    paths:
      - public
  only:
    - main