backend:
  name: gitlab
  repo: 2023/austin-utexas
  branch: main
  auth_type: pkce # Required for pkce
  app_id: 5a8e4b5cc1afac85d35f8072092326d5b85077fcd4a1e83a144c19bb0a88ba08 # Application ID from your GitLab settings
  api_root: https://gitlab.igem.org/api/v4
  base_url: https://gitlab.igem.org/
  auth_endpoint: oauth/authorize
media_folder: "/public/_media"
public_folder: "/austin-utexas/_media"
collections:
  - name: "page"
    label: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - label: "Sections"
      name: "sections"
      widget: "list"
      types:
        - label: "Carousel"
          name: "carousel"
          widget: object
          fields:
            - {label: Header, name: header, widget: string, default: "Image Gallery"}
            - {label: Template, name: template, widget: string, default: "carousel.html"}
        - label: "Spotlight"
          name: "spotlight"
          widget: object
          fields:
            - {label: Header, name: header, widget: string, default: "Spotlight"}
            - {label: Template, name: template, widget: string, default: "spotlight.html"}
            - {label: Text, name: text, widget: text, default: "Hello World"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
